[profile.default]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000
via_ir = true
src = "src"
test = "test"
libs = ["node_modules"]
fs_permissions = [{ access = "read-write", path = "../../deployments" }]

[profile.ci]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000
via_ir = true

[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"
